const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const nodemailer = require("nodemailer");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const app = express();
app.use(cors());
app.use(bodyParser.json());

const upload = multer({ storage: multer.memoryStorage() });

const transporter = nodemailer.createTransport({
  service: "AOL",
  auth: {
    user: "wasifhabib@aol.com",
    pass: "hejsemkbqajdchfk",
  },
});

function renderOrderHtml(order, orderId) {
  const safe = (v) => (v ? String(v) : "");
  return `
  <div style="font-family: Inter, Arial, sans-serif; background:#fff; padding:16px;">
    <h2 style="margin:0 0 12px; color:#111;">New Patch Order</h2>
    <p style="margin-bottom:12px;"><strong>Order ID:</strong> #${orderId}</p>
    <table style="width:100%; border-collapse:collapse;">
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Name</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.name)}</td></tr>
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Email</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.email)}</td></tr>
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Organization</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.organization)}</td></tr>
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Placement</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.patchSize)}</td></tr>
      ${order.customSize ? `<tr><td style="padding:8px; border:1px solid #eee;"><strong>Custom size</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.customSize)}</td></tr>` : ""}
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Quantity</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.quantity)}</td></tr>
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Contact number</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.contactNumber)}</td></tr>
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Needed by</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.deadline)}</td></tr>
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Reference URL</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.reference)}</td></tr>
      <tr><td style="padding:8px; border:1px solid #eee;"><strong>Design details</strong></td><td style="padding:8px; border:1px solid #eee;">${safe(order.designDetails)}</td></tr>
    </table>
    <p style="margin-top:12px; color:#555;">This email was auto‑generated by your Custom Dance Patches backend.</p>
  </div>`;
}

function getNextOrderId() {
  const filePath = path.join(__dirname, "order-id.txt");
  let currentId = 1000;
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, "utf8");
    currentId = parseInt(content.trim()) || 1000;
  }
  const nextId = currentId + 1;
  fs.writeFileSync(filePath, String(nextId));
  return nextId;
}

app.post("/api/orders", upload.single("artwork"), async (req, res) => {
  const order = req.body;
  const file = req.file;
  const orderId = getNextOrderId();

  try {
    await transporter.sendMail({
      from: '"Stacy from Custom Dance Patches" <wasifhabib@aol.com>',
      to: "wasifhabib@aol.com",
      subject: `New Patch Order #${orderId}`,
      text: `Order #${orderId} received:\n${JSON.stringify(order, null, 2)}`,
      html: renderOrderHtml(order, orderId),
      attachments: file ? [{ filename: file.originalname, content: file.buffer }] : [],
    });

    if (order.email) {
      await transporter.sendMail({
        from: '"Stacy from Custom Dance Patches" <wasifhabib@aol.com>',
        to: order.email,
        subject: `We received your patch request (#${orderId}) 🎉`,
        html: `
          <div style="font-family: Inter, Arial, sans-serif; background:#fff; padding:16px;">
            <h2 style="margin:0 0 12px; color:#111;">Thanks for your request!</h2>
            <p style="color:#333;">Your Order ID is <strong>#${orderId}</strong></p>
            <p style="color:#333;">We’ve received your details and will send a custom quote within 24–48 hours.</p>
            <p style="margin-top:8px; color:#555;">If you need to add anything, just reply to this email.</p>
            <hr style="border:none; border-top:1px solid #eee; margin:16px 0;" />
            <p style="color:#777; font-size:12px;">Custom Dance Patches</p>
          </div>
        `,
        text: `Thanks! We received your request. Your Order ID is #${orderId}. We'll send a quote within 24–48 hours.`,
      });
    }

    res.json({ message: "Order received successfully!", orderId });
  } catch {
    res.status(500).json({ message: "Error sending email" });
  }
});

app.listen(5000, () => console.log("Server running on http://localhost:5000"));